[package]
name = "fineleg"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
chrono = "0.4.39"
image = "0.25.5"
itertools = "0.14.0"
las = "0.9.3"
plotly = "0.12.1"
polars = { version = "0.45.1", features = ["cross_join", "json", "lazy", "random", "round_series"] }
reqwest = { version = "0.12.12", features = ["blocking", "json"] }
rerun = "0.21.0"
serde = "1.0.217"
serde_json = "1.0.135"
tokio = { version = "1.43.0", features = ["full"] }
