"""Make game source id unique

Revision ID: 14bb1b11c703
Revises: e52a3973b15a
Create Date: 2025-07-27 16:59:26.334990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14bb1b11c703'
down_revision: Union[str, None] = 'e52a3973b15a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'source_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'games', ['source_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='unique')
    op.alter_column('games', 'source_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
