"""Add sourceid to Deliveries

Revision ID: 523b339f520d
Revises: 2af5c7861f0e
Create Date: 2025-03-28 22:42:33.413262

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "523b339f520d"
down_revision: Union[str, None] = "2af5c7861f0e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("deliveries", sa.Column("source_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("deliveries", "source_id")
    # ### end Alembic commands ###
