"""After a false start, actually init the odata DB

Revision ID: 7006a6796cbc
Revises: 80d0f234bdbb
Create Date: 2025-03-22 16:30:44.503106

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7006a6796cbc"
down_revision: Union[str, None] = "80d0f234bdbb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "grounds",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("country", sa.String(length=255), nullable=True),
        sa.Column("_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "players",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "games",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column(
            "format",
            sa.Enum(
                "Test", "First Class", "ODI", "T20I", "T20 Domestic", name="format"
            ),
            nullable=True,
        ),
        sa.Column("ground_id", sa.UUID(), nullable=True),
        sa.Column("home_team_id", sa.UUID(), nullable=True),
        sa.Column("away_team_id", sa.UUID(), nullable=True),
        sa.Column("_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["away_team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ground_id"],
            ["grounds.id"],
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "deliveries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("competition", sa.String(length=255), nullable=True),
        sa.Column("game_id", sa.UUID(), nullable=True),
        sa.Column("innings", sa.Integer(), nullable=True),
        sa.Column("over", sa.Integer(), nullable=True),
        sa.Column("ball", sa.Integer(), nullable=True),
        sa.Column("batting_team_id", sa.UUID(), nullable=True),
        sa.Column("batsman_id", sa.UUID(), nullable=True),
        sa.Column("bowling_team_id", sa.UUID(), nullable=True),
        sa.Column("bowler_id", sa.UUID(), nullable=True),
        sa.Column("fielder", sa.String(length=255), nullable=True),
        sa.Column("batsman_hand", sa.Enum("Left", "Right", name="hand"), nullable=True),
        sa.Column("bowler_hand", sa.Enum("Left", "Right", name="hand"), nullable=True),
        sa.Column("bowling_style", sa.String(length=255), nullable=True),
        sa.Column("is_wicket", sa.Boolean(), nullable=True),
        sa.Column("dismissal_type", sa.String(length=255), nullable=True),
        sa.Column("dismissed_player_id", sa.UUID(), nullable=True),
        sa.Column("line", sa.String(length=255), nullable=True),
        sa.Column("length", sa.String(length=255), nullable=True),
        sa.Column("variation", sa.String(length=255), nullable=True),
        sa.Column("foot", sa.String(length=255), nullable=True),
        sa.Column("shot", sa.String(length=255), nullable=True),
        sa.Column("shot_type", sa.String(length=255), nullable=True),
        sa.Column("control", sa.String(length=255), nullable=True),
        sa.Column("shot_angle", sa.Float(), nullable=True),
        sa.Column("shot_magnitude", sa.Float(), nullable=True),
        sa.Column("fielding_position", sa.String(), nullable=True),
        sa.Column("fielding_action", sa.String(length=255), nullable=True),
        sa.Column("runs", sa.Integer(), nullable=True),
        sa.Column("runs_scored", sa.Integer(), nullable=True),
        sa.Column("runs_conceded", sa.Integer(), nullable=True),
        sa.Column("extras", sa.Integer(), nullable=True),
        sa.Column("commentary", sa.Text(), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("zone", sa.Text(), nullable=True),
        sa.Column("area", sa.Text(), nullable=True),
        sa.Column("len_var", sa.String(length=255), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("elevation", sa.String(length=255), nullable=True),
        sa.Column("_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["batsman_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["batting_team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["bowler_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["bowling_team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["dismissed_player_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("deliveries")
    op.drop_table("games")
    op.drop_table("teams")
    op.drop_table("players")
    op.drop_table("grounds")
    # ### end Alembic commands ###
