"""Move competition to game and limit fielder length

Revision ID: 2af5c7861f0e
Revises: 7006a6796cbc
Create Date: 2025-03-25 23:28:39.256416

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2af5c7861f0e"
down_revision: Union[str, None] = "7006a6796cbc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("deliveries", "competition")
    op.add_column("games", sa.Column("game_date", sa.Date(), nullable=True))
    op.add_column(
        "games", sa.Column("competition", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "games",
        sa.Column(
            "game_format",
            sa.Enum(
                "Test", "First Class", "ODI", "T20I", "T20 Domestic", name="game_format"
            ),
            nullable=True,
        ),
    )
    op.drop_column("games", "format")
    op.drop_column("games", "date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "games", sa.Column("date", sa.DATE(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "games",
        sa.Column(
            "format",
            postgresql.ENUM(
                "Test", "First Class", "ODI", "T20I", "T20 Domestic", name="format"
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("games", "game_format")
    op.drop_column("games", "competition")
    op.drop_column("games", "game_date")
    op.add_column(
        "deliveries",
        sa.Column(
            "competition", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
