"""Remove enums

Revision ID: 9ba48e61a43a
Revises: 4dfa848f1db6
Create Date: 2025-03-29 16:59:33.000659

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9ba48e61a43a"
down_revision: Union[str, None] = "4dfa848f1db6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "deliveries",
        "batsman_hand",
        existing_type=postgresql.ENUM("Left", "Right", name="hand"),
        type_=sa.String(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "deliveries",
        "bowler_hand",
        existing_type=postgresql.ENUM("Left", "Right", name="hand"),
        type_=sa.String(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "games",
        "game_format",
        existing_type=postgresql.ENUM(
            "Test", "First Class", "ODI", "T20I", "T20 Domestic", name="game_format"
        ),
        type_=sa.String(length=255),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "games",
        "game_format",
        existing_type=sa.String(length=255),
        type_=postgresql.ENUM(
            "Test", "First Class", "ODI", "T20I", "T20 Domestic", name="game_format"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "deliveries",
        "bowler_hand",
        existing_type=sa.String(length=255),
        type_=postgresql.ENUM("Left", "Right", name="hand"),
        existing_nullable=True,
    )
    op.alter_column(
        "deliveries",
        "batsman_hand",
        existing_type=sa.String(length=255),
        type_=postgresql.ENUM("Left", "Right", name="hand"),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
