"""Make delivery source_id unique

Revision ID: e52a3973b15a
Revises: 9ba48e61a43a
Create Date: 2025-03-30 22:10:12.602159

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e52a3973b15a"
down_revision: Union[str, None] = "9ba48e61a43a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "deliveries", ["source_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "deliveries", type_="unique")
    # ### end Alembic commands ###
