[project]
name = "firstslip"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fiftyone>=1.9.0",
    "opencv-python>=4.11.0.86",
    "plotly>=6.0.0",
    "pycocotools>=2.0.10",
    "ruff>=0.9.6",
    "streamlit>=1.42.0",
    "ultralytics>=8.3.223",
    "wonderwords>=3.0.1",
]

[tool.ruff]
line-length = 120
