CREATE TABLE odata_RAW (
	idk INT,
	fixtureId INT,
	team1 TEXT,
	team2 TEXT,
	matchDate TEXT,
	format TEXT,
	ground TEXT,
	country TEXT,
	inns INT,
	battingTeam TEXT,
	bowlingTeam TEXT,
	batsman TEXT,
	bowler TEXT,
	batsmanHand TEXT,
	bowlerHand TEXT,
	bowlerType TEXT,
	over INT,
	ball INT,
	dismissalType TEXT,
	dismissedPlayer TEXT,
	shot_angle FLOAT,
	shot_magnitude FLOAT,
	fielding_position TEXT,
	runs_conceded FLOAT,
	runs INT,
	runs_scored FLOAT,
	extras INT,
	is_wicket INT,
	commentary TEXT,
	timestamp TEXT,
	competition TEXT,
	len_var TEXT,
	shot TEXT,
	zone TEXT,
	shot_type TEXT,
	variation TEXT,
	length TEXT,
	area TEXT,
	control TEXT,
	line TEXT,
	foot TEXT,
	fielder_action TEXT,
	fielder TEXT,
	elevation TEXT,
	year TEXT,
	ctrl INT,
	ballfaced INT
);

ALTER TABLE odata_RAW
ALTER COLUMN YEAR TYPE TEXT;

COPY odata_RAW FROM '/data/odata_full.csv' DELIMITER ',' CSV HEADER;
