# -*- coding: utf-8 -*-
"""autogluon_mm_finetune.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1652pRL4Z92nPa_TPo3oJ3bbr8umvyKD_
"""

# Commented out IPython magic to ensure Python compatibility.
# Step 1: Install dependencies

# %pip install autogluon --extra-index-url https://download.pytorch.org/whl/cpu
!python -m mim install "mmcv==2.1.0"
# %pip install "mmdet==3.2.0"

# Step 2: Imports and fixes
import torch
import glob
from autogluon.multimodal import MultiModalPredictor


# We have to monkeypatch torch.load since it seems Autogluon didn't correctly update their usage since pytorch 2.6's changes to weights_only default
original_load = torch.load
def load_with_weights_only_false(*args, **kwargs):
    kwargs.setdefault("weights_only", False)
    return original_load(*args, **kwargs)
torch.load = load_with_weights_only_false

"""Step 3: Upload folder with data using left sidebar. File structure within folder needs to be correct for Autogluon to work"""

# Train
# TODO: Find out how to reduce number of epochs so this doesn't take so long
train_path = next((p for p in glob.iglob("/content/**/*.json", recursive=True) if "/sample_data/" not in p))
print(f"Using COCO json found at: {train_path}")
predictor = MultiModalPredictor(problem_type="object_detection", sample_data_path=train_path)
predictor.fit(train_path)

# See training summary
predictor.fit_summary(verbosity=3)